#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use App\Commands\AddProblemCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new AddProblemCommand());

$application->run();
